prepare:
  data_url: "https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv"
  data_file: "raw.csv"
  test_size: 0.2
  random_state: 42

train:
  alpha: 0.5
  l1_ratio: 0.5
  random_state: 42

evaluate:
  model_file: "model.joblib"
  test_file: "data/test.csv"